from __future__ import annotations

SETUP_PAGE = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Threatline setup</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#e7e9ee;background:#0d0f13;color-scheme:dark}*{box-sizing:border-box}body{margin:0}.shell{max-width:980px;margin:auto;padding:34px 24px 60px}.eyebrow{color:#8490a4;font-size:12px;text-transform:uppercase;letter-spacing:.12em}.brand{font-size:25px;font-weight:760;letter-spacing:-.03em}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}.top a{color:#aeb9ff;text-decoration:none}.top a:hover{text-decoration:underline}.hero{padding:42px 0 24px;border-bottom:1px solid #242a34}.hero h1{font-size:38px;margin:5px 0 8px;letter-spacing:-.04em}.hero p,.muted{color:#929daf}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:24px 0}.step{border:1px solid #29313c;border-radius:12px;padding:13px;background:#13171d}.step strong{display:block;margin-top:4px}.panel{border:1px solid #29313c;border-radius:14px;padding:20px;background:#13171d;margin:14px 0}.panel h2{font-size:18px;margin:0 0 6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:flex;flex-direction:column;gap:6px}.field label{font-size:12px;color:#9ba6b8}.field input,.field select,.field textarea{background:#10141a;color:#e7e9ee;border:1px solid #303844;border-radius:9px;padding:10px 11px;width:100%;font:inherit}.field textarea{min-height:80px;resize:vertical}.provider{border-top:1px solid #252c36;padding-top:18px;margin-top:18px}.provider-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.toggle{display:flex;align-items:center;gap:8px;color:#d7dce5}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.button{border:1px solid #333b47;border-radius:9px;background:#171b22;color:#c5cdd9;padding:10px 14px;cursor:pointer;font:inherit}.button.primary{background:#e9edf5;color:#11151b;border-color:#e9edf5}.status{min-height:20px;color:#9be7b2;font-size:13px;margin-top:10px}.status.bad{color:#ff9e91}.existing{display:flex;gap:10px;align-items:end;margin-top:18px}.existing .field{flex:1}.credential-note{font-size:11px;color:#7f8b9e;margin-top:4px}.provider-note{font-size:12px;color:#7f8b9e;margin-top:8px}:focus-visible{outline:2px solid #9fb3ff;outline-offset:2px}@media(max-width:720px){.grid,.steps{grid-template-columns:1fr}.existing{align-items:stretch;flex-direction:column}.hero h1{font-size:31px}.provider-head{align-items:flex-start;flex-direction:column}.toggle{padding:5px 0}}
</style>
</head>
<body>
<main class="shell">
<header class="top"><div><div class="eyebrow">Engineering operations</div><div class="brand">Threatline</div></div><a href="/">Workspace</a></header>
<section class="hero"><div class="eyebrow">First-run setup</div><h1>Connect the systems you already use.</h1><p>Workspace settings stay local. Provider credentials are stored separately from ordinary configuration and are never returned by the setup API.</p></section>
<section class="steps" aria-label="Setup steps"><div class="step"><span class="eyebrow">Step 1</span><strong>Name the workspace</strong><div class="muted">Keep teams and environments distinct.</div></div><div class="step"><span class="eyebrow">Step 2</span><strong>Connect providers</strong><div class="muted">Demo mode needs no credentials.</div></div><div class="step"><span class="eyebrow">Step 3</span><strong>Verify and continue</strong><div class="muted">Test connections before saving.</div></div></section>
<section class="panel"><h2>Workspace</h2><div class="grid"><div class="field"><label for="workspaceName">Workspace name</label><input id="workspaceName" value="Local workspace" autocomplete="off"></div><div class="field"><label for="workspaceId">Workspace ID</label><input id="workspaceId" placeholder="local-workspace" autocomplete="off"></div></div><div class="existing"><div class="field"><label for="workspaceSelect">Existing workspaces</label><select id="workspaceSelect"><option value="">New workspace</option></select></div><button id="activateWorkspace" type="button" class="button">Activate selected</button></div></section>
<section class="panel"><h2>Providers</h2><div class="muted">Enable only what this workspace needs. You can return to this page later.</div>
<div class="provider"><div class="provider-head"><div><strong>Demo</strong><div class="muted">Fictional operational data for immediate evaluation.</div></div><label class="toggle"><input id="demoEnabled" type="checkbox" checked> Enabled</label></div><div class="actions"><button type="button" class="button" data-test="demo">Test demo provider</button></div><div id="demoStatus" class="status" role="status" aria-live="polite"></div></div>
<div class="provider"><div class="provider-head"><div><strong>Jira</strong><div class="muted">Cloud, Server, or Data Center through the existing Jira provider.</div></div><label class="toggle"><input id="jiraEnabled" type="checkbox"> Enabled</label></div><div class="grid"><div class="field"><label for="jiraUrl">Base URL</label><input id="jiraUrl" placeholder="https://jira.example.com"></div><div class="field"><label for="jiraJql">JQL</label><input id="jiraJql" placeholder="project = OPS AND statusCategory != Done"></div><div class="field"><label for="jiraEmail">Email for API-token auth</label><input id="jiraEmail" type="email" autocomplete="username"></div><div class="field"><label for="jiraApiToken">API token</label><input id="jiraApiToken" type="password" autocomplete="new-password"><div id="jiraApiTokenNote" class="credential-note"></div></div><div class="field"><label for="jiraPat">Bearer token / PAT</label><input id="jiraPat" type="password" autocomplete="new-password"><div id="jiraPatNote" class="credential-note"></div></div><div class="field"><label for="jiraVerify">TLS verification</label><select id="jiraVerify"><option value="true">Verify certificates</option><option value="false">Allow unverified certificates</option></select></div></div><div class="actions"><button type="button" class="button" data-test="jira">Test Jira connection</button></div><div id="jiraStatus" class="status" role="status" aria-live="polite"></div></div>
<div class="provider"><div class="provider-head"><div><strong>GitHub</strong><div class="muted">GitHub.com or GitHub Enterprise Server repositories and source context.</div></div><label class="toggle"><input id="githubEnabled" type="checkbox"> Enabled</label></div><div class="grid"><div class="field"><label for="githubRepos">Repositories</label><textarea id="githubRepos" placeholder="owner/service-api, owner/platform-runbooks"></textarea></div><div class="field"><label for="githubToken">Token</label><input id="githubToken" type="password" autocomplete="new-password"><div id="githubTokenNote" class="credential-note"></div></div><div class="field"><label for="githubApi">API URL</label><input id="githubApi" value="https://api.github.com"></div><div class="field"><label for="githubWeb">Web URL</label><input id="githubWeb" value="https://github.com"></div><div class="field"><label for="githubVerify">TLS verification</label><select id="githubVerify"><option value="true">Verify certificates</option><option value="false">Allow unverified certificates</option></select></div></div><div class="actions"><button type="button" class="button" data-test="github">Test GitHub connection</button></div><div id="githubStatus" class="status" role="status" aria-live="polite"></div></div>
<div class="provider"><div class="provider-head"><div><strong>Grafana</strong><div class="muted">Link dashboards into investigations without copying metrics into Threatline.</div></div><label class="toggle"><input id="grafanaEnabled" type="checkbox"> Enabled</label></div><div class="grid"><div class="field"><label for="grafanaUrl">Base URL</label><input id="grafanaUrl" placeholder="https://grafana.example.com"></div><div class="field"><label for="grafanaOrgId">Organization ID (optional)</label><input id="grafanaOrgId" placeholder="1"></div><div class="field"><label for="grafanaDashboards">Dashboards</label><textarea id="grafanaDashboards" placeholder="checkout-api|checkout-overview|Checkout Overview; fleet|Fleet Overview"></textarea></div><div class="field"><label for="grafanaServiceVariable">Service variable</label><input id="grafanaServiceVariable" value="service"></div><div class="field"><label for="grafanaFrom">Default time range start</label><input id="grafanaFrom" value="now-6h"></div><div class="field"><label for="grafanaTo">Default time range end</label><input id="grafanaTo" value="now"></div></div><div class="provider-note">Use <code>uid|title</code> for global dashboards or <code>service_id|uid|title</code> for service-scoped dashboards. Separate entries with semicolons.</div><div class="actions"><button type="button" class="button" data-test="grafana">Test Grafana configuration</button></div><div id="grafanaStatus" class="status" role="status" aria-live="polite"></div></div>
<div class="provider"><div class="provider-head"><div><strong>Zabbix</strong><div class="muted">Optional active-problem ingestion correlated by a service tag.</div></div><label class="toggle"><input id="zabbixEnabled" type="checkbox"> Enabled</label></div><div class="grid"><div class="field"><label for="zabbixUrl">Base URL</label><input id="zabbixUrl" placeholder="https://zabbix.example.com"></div><div class="field"><label for="zabbixApiToken">API token</label><input id="zabbixApiToken" type="password" autocomplete="new-password"><div id="zabbixApiTokenNote" class="credential-note"></div></div><div class="field"><label for="zabbixServiceTag">Service tag</label><input id="zabbixServiceTag" value="service"></div><div class="field"><label for="zabbixVerify">TLS verification</label><select id="zabbixVerify"><option value="true">Verify certificates</option><option value="false">Allow unverified certificates</option></select></div></div><div class="actions"><button type="button" class="button" data-test="zabbix">Test Zabbix connection</button></div><div id="zabbixStatus" class="status" role="status" aria-live="polite"></div></div>
</section>
<section class="panel"><h2>Finish</h2><div class="muted">Saving activates this workspace immediately. Blank credential fields preserve credentials already stored for an existing workspace.</div><div class="actions"><button id="saveWorkspace" type="button" class="button primary">Save and open Threatline</button></div><div id="saveStatus" class="status" role="status" aria-live="polite"></div></section>
</main>
<script>
const byId=id=>document.getElementById(id);let state={workspaces:[],active_workspace:null};
function providerConfig(name){if(name==='demo')return{enabled:byId('demoEnabled').checked};if(name==='jira')return{enabled:byId('jiraEnabled').checked,base_url:byId('jiraUrl').value.trim(),jql:byId('jiraJql').value.trim(),email:byId('jiraEmail').value.trim(),verify_ssl:byId('jiraVerify').value==='true'};if(name==='github')return{enabled:byId('githubEnabled').checked,repositories:byId('githubRepos').value.split(',').map(v=>v.trim()).filter(Boolean),api_url:byId('githubApi').value.trim(),web_url:byId('githubWeb').value.trim(),verify_ssl:byId('githubVerify').value==='true'};if(name==='grafana')return{enabled:byId('grafanaEnabled').checked,base_url:byId('grafanaUrl').value.trim(),dashboards:byId('grafanaDashboards').value.trim(),org_id:byId('grafanaOrgId').value.trim(),service_variable:byId('grafanaServiceVariable').value.trim(),default_from:byId('grafanaFrom').value.trim(),default_to:byId('grafanaTo').value.trim()};if(name==='zabbix')return{enabled:byId('zabbixEnabled').checked,base_url:byId('zabbixUrl').value.trim(),service_tag:byId('zabbixServiceTag').value.trim(),verify_ssl:byId('zabbixVerify').value==='true'};return{}}
function providerSecrets(name){if(name==='jira')return{api_token:byId('jiraApiToken').value,bearer_token:byId('jiraPat').value};if(name==='github')return{token:byId('githubToken').value};if(name==='zabbix')return{api_token:byId('zabbixApiToken').value};return{}}
async function request(url,payload){const options=payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{};const response=await fetch(url,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||'Request failed');return data}
function setStatus(name,message,ok=true){const el=byId(name+'Status');el.textContent=message;el.classList.toggle('bad',!ok)}
function fillWorkspace(workspace){if(!workspace){byId('workspaceId').value='';byId('workspaceName').value='Local workspace';return}byId('workspaceId').value=workspace.id||'';byId('workspaceName').value=workspace.name||'Local workspace';const providers=workspace.providers||{};const demo=providers.demo||{},jira=providers.jira||{},github=providers.github||{},grafana=providers.grafana||{},zabbix=providers.zabbix||{};byId('demoEnabled').checked=!!demo.enabled;byId('jiraEnabled').checked=!!jira.enabled;byId('jiraUrl').value=jira.base_url||'';byId('jiraJql').value=jira.jql||'';byId('jiraEmail').value=jira.email||'';byId('jiraVerify').value=String(jira.verify_ssl!==false);byId('githubEnabled').checked=!!github.enabled;byId('githubRepos').value=(github.repositories||[]).join(', ');byId('githubApi').value=github.api_url||'https://api.github.com';byId('githubWeb').value=github.web_url||'https://github.com';byId('githubVerify').value=String(github.verify_ssl!==false);byId('grafanaEnabled').checked=!!grafana.enabled;byId('grafanaUrl').value=grafana.base_url||'';byId('grafanaDashboards').value=typeof grafana.dashboards==='string'?grafana.dashboards:'';byId('grafanaOrgId').value=grafana.org_id||'';byId('grafanaServiceVariable').value=grafana.service_variable||'service';byId('grafanaFrom').value=grafana.default_from||'now-6h';byId('grafanaTo').value=grafana.default_to||'now';byId('zabbixEnabled').checked=!!zabbix.enabled;byId('zabbixUrl').value=zabbix.base_url||'';byId('zabbixServiceTag').value=zabbix.service_tag||'service';byId('zabbixVerify').value=String(zabbix.verify_ssl!==false);byId('jiraApiToken').value='';byId('jiraPat').value='';byId('githubToken').value='';byId('zabbixApiToken').value='';byId('jiraApiTokenNote').textContent=jira.credential_fields&&jira.credential_fields.api_token?'Stored credential will be kept if left blank.':'';byId('jiraPatNote').textContent=jira.credential_fields&&jira.credential_fields.bearer_token?'Stored credential will be kept if left blank.':'';byId('githubTokenNote').textContent=github.credential_fields&&github.credential_fields.token?'Stored credential will be kept if left blank.':'';byId('zabbixApiTokenNote').textContent=zabbix.credential_fields&&zabbix.credential_fields.api_token?'Stored credential will be kept if left blank.':''}
async function loadState(){state=await request('/api/setup');const select=byId('workspaceSelect');select.innerHTML='<option value="">New workspace</option>'+state.workspaces.map(w=>`<option value="${w.id}">${w.name}${w.id===state.active_workspace?' (active)':''}</option>`).join('');if(state.active_workspace){select.value=state.active_workspace;fillWorkspace(state.workspaces.find(w=>w.id===state.active_workspace))}}
async function testProvider(name){setStatus(name,'Testing…');try{const payload={provider:name,workspace_id:byId('workspaceId').value.trim(),config:providerConfig(name),secrets:providerSecrets(name)};const result=await request('/api/setup/test',payload);setStatus(name,`${result.health.status}: ${result.health.detail}`,result.health.status==='healthy')}catch(error){setStatus(name,error.message,false)}}
document.querySelectorAll('[data-test]').forEach(button=>button.onclick=()=>testProvider(button.dataset.test));
byId('workspaceSelect').onchange=()=>{const workspace=state.workspaces.find(w=>w.id===byId('workspaceSelect').value);fillWorkspace(workspace)};
byId('activateWorkspace').onclick=async()=>{const workspace_id=byId('workspaceSelect').value;if(!workspace_id)return setStatus('save','Choose an existing workspace first.',false);try{await request('/api/setup/activate',{workspace_id});location.href='/'}catch(error){setStatus('save',error.message,false)}};
byId('saveWorkspace').onclick=async()=>{setStatus('save','Saving…');const providers={demo:providerConfig('demo'),jira:providerConfig('jira'),github:providerConfig('github'),grafana:providerConfig('grafana'),zabbix:providerConfig('zabbix')};const secrets={jira:providerSecrets('jira'),github:providerSecrets('github'),zabbix:providerSecrets('zabbix')};try{await request('/api/setup/workspace',{workspace_id:byId('workspaceId').value.trim(),name:byId('workspaceName').value.trim(),providers,secrets,activate:true});location.href='/'}catch(error){setStatus('save',error.message,false)}};
loadState().catch(error=>setStatus('save',error.message,false));
</script>
</body>
</html>'''
