from __future__ import annotations

from typing import Protocol

from threatline.domain import Alert, Change, Decision, Meeting, Runbook, Service, WorkItem


class ContextProvider(Protocol):
    """Read-only boundary for systems that contribute operational context."""

    name: str

    def services(self) -> list[Service]: ...
    def work_items(self) -> list[WorkItem]: ...
    def alerts(self) -> list[Alert]: ...
    def changes(self) -> list[Change]: ...
    def runbooks(self) -> list[Runbook]: ...
    def meetings(self) -> list[Meeting]: ...
    def decisions(self) -> list[Decision]: ...
